# Generated by Django 2.2.5 on 2022-08-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='langge',
            new_name='language',
        ),
    ]
