# Generated by Django 2.2.5 on 2022-08-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.TimeField(null=True),
        ),
    ]
